spring:
  config:
    import: optional:file:env/.env[.properties]
  application:
    name: "OFFICE-AGENT"
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
app:
  jwt:
    secret: ${JWT_SECRET}